name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - ipykernel

  - black
  - isort
  - nbqa

  - pandas
  - scikit-learn
  - seaborn

  - requests
  - flask
  - fastapi
  - gunicorn
